# coding: utf-8

"""
    Impower ERP

     # Setup  Enquire a `Bearer Token` from Api Support  # Authentication  Use API calls with an `Authorization: Bearer TOKEN` header  # Webhooks  The application supports sending secured notification events to registered endpoints.  The events one may receive are sent as  ``` POST https://your.webhook.url/path/somewhere Authorization: Bearer TOKEN  {   \"connectionId\": 0,   \"entityType\": \"properties|contacts|invoices|etc.\",   \"entityId\": 0,   \"eventType\": \"CREATE|UPDATE|DELETE\" } ```  <!-- Style overrides --> <style> code {   display: block; } </style>   # noqa: E501

    OpenAPI spec version: 2.201.52181d67
    Contact: support+api@impower.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import impower_client
from impower_client.api.document_api_api import DocumentAPIApi  # noqa: E501
from impower_client.rest import ApiException


class TestDocumentAPIApi(unittest.TestCase):
    """DocumentAPIApi unit test stubs"""

    def setUp(self):
        self.api = DocumentAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_document_by_upload_using_post(self):
        """Test case for create_document_by_upload_using_post

        Create a new document based on given the file  # noqa: E501
        """
        pass

    def test_delete_document_using_delete(self):
        """Test case for delete_document_using_delete

        Delete an existing document based on the given id  # noqa: E501
        """
        pass

    def test_download_documents_by_filter_using_get(self):
        """Test case for download_documents_by_filter_using_get

        Download multiple documents by given filter conditions  # noqa: E501
        """
        pass

    def test_download_using_get(self):
        """Test case for download_using_get

        Download a single document by given id  # noqa: E501
        """
        pass

    def test_get_documents_by_filter_using_get(self):
        """Test case for get_documents_by_filter_using_get

        Get documents by the given filter parameters  # noqa: E501
        """
        pass

    def test_update_documents_using_put(self):
        """Test case for update_documents_using_put

        Update an existing document based on the given request body  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
