# coding: utf-8

"""
    Impower ERP

     # Setup  Enquire a `Bearer Token` from Api Support  # Authentication  Use API calls with an `Authorization: Bearer TOKEN` header  # Webhooks  The application supports sending secured notification events to registered endpoints.  The events one may receive are sent as  ``` POST https://your.webhook.url/path/somewhere Authorization: Bearer TOKEN  {   \"connectionId\": 0,   \"entityType\": \"properties|contacts|invoices|etc.\",   \"entityId\": 0,   \"eventType\": \"CREATE|UPDATE|DELETE\" } ```  <!-- Style overrides --> <style> code {   display: block; } </style>   # noqa: E501

    OpenAPI spec version: 2.201.52181d67
    Contact: support+api@impower.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import impower_client
from impower_client.api.document_tag_api_api import DocumentTagAPIApi  # noqa: E501
from impower_client.rest import ApiException


class TestDocumentTagAPIApi(unittest.TestCase):
    """DocumentTagAPIApi unit test stubs"""

    def setUp(self):
        self.api = DocumentTagAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_document_tag_using_post(self):
        """Test case for create_document_tag_using_post

        Create a new document tag  # noqa: E501
        """
        pass

    def test_delete_document_tag_using_delete(self):
        """Test case for delete_document_tag_using_delete

        Delete an existing document tag based on the given id  # noqa: E501
        """
        pass

    def test_get_document_tags_using_get(self):
        """Test case for get_document_tags_using_get

        Get document tags  # noqa: E501
        """
        pass

    def test_update_document_tag_using_put(self):
        """Test case for update_document_tag_using_put

        Update an existing document tag based on the given id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
