# coding: utf-8

"""
    Impower ERP

     # Setup  Enquire a `Bearer Token` from Api Support  # Authentication  Use API calls with an `Authorization: Bearer TOKEN` header  # Webhooks  The application supports sending secured notification events to registered endpoints.  The events one may receive are sent as  ``` POST https://your.webhook.url/path/somewhere Authorization: Bearer TOKEN  {   \"connectionId\": 0,   \"entityType\": \"properties|contacts|invoices|etc.\",   \"entityId\": 0,   \"eventType\": \"CREATE|UPDATE|DELETE\" } ```  <!-- Style overrides --> <style> code {   display: block; } </style>   # noqa: E501

    OpenAPI spec version: 2.201.52181d67
    Contact: support+api@impower.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "impower-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Impower ERP",
    author_email="support+api@impower.de",
    url="",
    keywords=["Swagger", "Impower ERP"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
     # Setup  Enquire a &#x60;Bearer Token&#x60; from Api Support  # Authentication  Use API calls with an &#x60;Authorization: Bearer TOKEN&#x60; header  # Webhooks  The application supports sending secured notification events to registered endpoints.  The events one may receive are sent as  &#x60;&#x60;&#x60; POST https://your.webhook.url/path/somewhere Authorization: Bearer TOKEN  {   \&quot;connectionId\&quot;: 0,   \&quot;entityType\&quot;: \&quot;properties|contacts|invoices|etc.\&quot;,   \&quot;entityId\&quot;: 0,   \&quot;eventType\&quot;: \&quot;CREATE|UPDATE|DELETE\&quot; } &#x60;&#x60;&#x60;  &lt;!-- Style overrides --&gt; &lt;style&gt; code {   display: block; } &lt;/style&gt;   # noqa: E501
    """
)
