# coding: utf-8

# flake8: noqa
"""
    Impower ERP

     # Setup  Enquire a `Bearer Token` from Api Support  # Authentication  Use API calls with an `Authorization: Bearer TOKEN` header  # Webhooks  The application supports sending secured notification events to registered endpoints.  The events one may receive are sent as  ``` POST https://your.webhook.url/path/somewhere Authorization: Bearer TOKEN  {   \"connectionId\": 0,   \"entityType\": \"properties|contacts|invoices|etc.\",   \"entityId\": 0,   \"eventType\": \"CREATE|UPDATE|DELETE\" } ```  <!-- Style overrides --> <style> code {   display: block; } </style>   # noqa: E501

    OpenAPI spec version: 2.201.52181d67
    Contact: support+api@impower.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from impower_client.models.contact_details_dto import ContactDetailsDto
from impower_client.models.contact_dto import ContactDto
from impower_client.models.contact_simple_dto import ContactSimpleDto
from impower_client.models.contract_dto import ContractDto
from impower_client.models.document_dto import DocumentDto
from impower_client.models.document_tag_create_dto import DocumentTagCreateDto
from impower_client.models.document_tag_dto import DocumentTagDto
from impower_client.models.document_tag_simple_dto import DocumentTagSimpleDto
from impower_client.models.document_tag_update_dto import DocumentTagUpdateDto
from impower_client.models.document_update_dto import DocumentUpdateDto
from impower_client.models.documents_upload_body import DocumentsUploadBody
from impower_client.models.error_code_details_dto import ErrorCodeDetailsDto
from impower_client.models.invoice_dto import InvoiceDto
from impower_client.models.invoice_item_dto import InvoiceItemDto
from impower_client.models.invoice_item_update_dto import InvoiceItemUpdateDto
from impower_client.models.invoice_update_dto import InvoiceUpdateDto
from impower_client.models.invoices_upload_body import InvoicesUploadBody
from impower_client.models.page_of_contact_dto import PageOfContactDto
from impower_client.models.page_of_contract_dto import PageOfContractDto
from impower_client.models.page_of_document_dto import PageOfDocumentDto
from impower_client.models.page_of_invoice_dto import PageOfInvoiceDto
from impower_client.models.page_of_property_dto import PageOfPropertyDto
from impower_client.models.page_of_unit_dto import PageOfUnitDto
from impower_client.models.pageable import Pageable
from impower_client.models.property_dto import PropertyDto
from impower_client.models.sort import Sort
from impower_client.models.unit_dto import UnitDto
